apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  limits:
  - default:
      memory: 50Mi
      cpu: 0.1
    defaultRequest:
      memory: 30Mi
      cpu: 0.05
    max:
      memory: 80Mi
      cpu: 0.1
    min:
      memory: 10Mi
      cpu: 0.05
    type: Container