apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  limits:
  - default:
      memory: 150Mi
      cpu: 0.5
    defaultRequest:
      memory: 150Mi
      cpu: 0.5
    max:
      memory: 300Mi
      cpu: 1
    min:
      memory: 150Mi
      cpu: 0.5
    type: Container