apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev
  namespace: {{ .Values.namespace }}-dev
  annotations:
    "helm.sh/hook": pre-install
spec:
  hard:
    requests.cpu: 2
    requests.memory: 400Mi
    limits.cpu: 2
    limits.memory: 500Mi
    pods: 10
    services.nodeports: "0"
