apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-frontend-ingress
  namespace: chat
spec:
  ingressClassName: nginx  # Specifies the Ingress controller to use
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chat-frontend-service
            # namespace: chat
            port:
              number: 4200  # The port exposed by the chat-frontend-service
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: chat-websocket-service
            # namespace: chat
            port:
              number: 8080
      